logging:
  level:
    web: DEBUG
    security: DEBUG
    sql: DEBUG

server:
  port: 9000

spring:
  application:
    name: authorization-server

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/high-five}
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  sql:
    init:
      mode: always
      platform: postgres

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        client:
          high-five:
            registration:
              client-id:  high-five
              client-authentication-methods:
                - none
              authorization-grant-types:
                - authorization_code
              redirect-uris:
                - http://localhost:3000
              scopes:
                - openid
                - profile
            require-authorization-consent: true
            require-proof-key: true