eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 9000

spring:
  application:
    name: authorization-server

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        client:
          public-client:
            registration:
              client-id: high-five
              client-authentication-methods:
                - none
              authorization-grant-types:
                - authorization_code
              redirect-uris:
                - http://localhost:3000
              scopes:
                - openid
                - profile
            require-authorization-consent: true
            require-proof-key: true
  sql:
    init:
      mode: always
      platform: postgres
