logging:
  level:
    web: DEBUG
    security: DEBUG
    sql: DEBUG

server:
  port: 8080

spring:
  application:
    name: authorization-server

  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080
        client:
          high-five:
            registration:
              client-id:  high-five
              client-authentication-methods:
                - none
              authorization-grant-types:
                - authorization_code
              redirect-uris:
                - http://localhost:3000
              scopes:
                - openid
                - profile
            require-authorization-consent: true
            require-proof-key: true