BEGIN TRANSACTION;

-- INSERT INTO client (
--     client_id,
--     client_secret,
--     client_name,
--     client_authentication_methods,
--     authorization_grant_types,
--     redirect_uris,
--     scopes,
--     client_settings,
--     token_settings
-- ) VALUES (
--     'high-five',
--     'none',
--     'high-five',
--     'none',
--     'authorization_code',
--     'http://localhost:3000',
--     'openid,profile',
--     '{"@class":"java.util.HashMap","settings.client.require-proof-key":true,"settings.client.require-authorization-consent":true}',
--     '{"@class":"java.util.HashMap","settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.reuse-refresh-tokens":true,"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"]}'
-- );

-- INSERT INTO users (
--     username,
--     email,
--     password
-- ) VALUES (
--     'singhalmradul',
--     'singhalmradul@gmail.com',
--     '{noop}Aa1@@1aA'
-- ), (
--     'hawksea',
--     'hawksea@email.io',
--     '{bcrypt}$2a$10$3ypI1XDt6y0gmOTqZHUeMOAZzLo5JNU5ZurS0r9/2GwXIf1qUucEq'
-- ), (
--     'saltsamuel',
--     'saltsamuel@email.io',
--     '{bcrypt}$2y$10$naD37Mw1bMr94TcOdlRusuLLY.Ke96lnWCkMbOZpagtWo3UPJk5WO'
-- ), (
--     'markelharry',
--     'markelharry@email.io',
--     '{bcrypt}$2a$10$PIfJo8tkpzbSyrCrVS8cKO9rUOdm4FUNBL1qQD2onNC5abWX75V9.'
-- ), (
--     'adamsmorgan',
--     'adamsmorgan@email.io',
--     '{bcrypt}$2a$10$8hxqrRHYwUAMkFhr.oAnLeELSdD5mIIihLhlkgh37k38gAeakRoSi'
-- );

-- INSERT INTO authorities (
--     username,
--     authority
-- ) VALUES (
--     'user',
--     'ROLE_USER'
-- ), (
--     'hawksea',
--     'ROLE_USER'
-- ), (
--     'saltsamuel',
--     'ROLE_USER'
-- ), (
--     'markelharry',
--     'ROLE_USER'
-- ), (
--     'adamsmorgan',
--     'ROLE_USER'
-- );


COMMIT;